FROM golang:1.19 as builder
WORKDIR /ticketservice
COPY go.* ./
RUN go mod download
COPY .  ./

RUN ECHO $GOROOT

RUN pwd
RUN go run compilePlugins.go
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=readonly -v -o ticketservice

FROM gcr.io/distroless/static

COPY --from=builder /ticketservice /ticketservice

CMD ["/ticketservice"]